version: '3.7'
services:
  gateway:
    build: .
    restart: unless-stopped
    container_name: gateway
    ports:
      - 3000:3000
    environment:
      - DECONCENTRATOR_ENDPOINT
      - REGISTRY_ENDPOINT
      - DATABASE_ENDPOINT
networks:
  default:
    external:
      name: beuthbot_network